name: Merge Clash Subscription & JS Script

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout 仓库
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ 下载订阅链接（通过 Secret 保存）
      - name: Download subscription
        run: |
          # SUB_LINK="${{ secrets.SUB_LINK }}"
          SUB_LINK="https://proxyinfo.net/api/v1/client/subscribe?token=e4921e435c8e2651c128f3e974a9cca4&flag=clash"
          curl -L "$SUB_LINK" -o subscription.yaml
          echo "✅ Subscription downloaded"

      # 3️⃣ 启动 Sub-Store Docker 容器，挂载 workspace 目录
      - name: Start Sub-Store
        run: |
          mkdir -p ${{ github.workspace }}/substore-data
          docker run -d --name substore -p 3000:3000 -p 3001:3001 \
            -v ${{ github.workspace }}/substore-data:/root/sub-store \
            xream/sub-store:latest
          sleep 10
          docker logs substore
          curl -s http://localhost:3000/api/version

      # 4️⃣ 将脚本和订阅文件拷贝到挂载目录
      - name: Prepare files for Sub-Store
        run: |
          cp clash.js substore-data/
          cp subscription.yaml substore-data/

      # 5️⃣ 合并订阅 + JS 脚本
      - name: Merge with JS script
        run: |
          curl -L "http://localhost:3000/sub?target=clash&url=/root/sub-store/subscription.yaml&config=/root/sub-store/script.js" -o substore-data/merged.yaml
          echo "✅ Merged YAML created"

      # 6️⃣ 推送到 gh-pages 分支
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: substore-data
          force_orphan: true
