name: Merge Clash Subscription & JS Script

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout 仓库
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ 启动 Sub-Store Docker 容器
      - name: Start Sub-Store
        run: |
          docker run -d --name substore -p 25500:25500 \
            -v ${{ github.workspace }}/data:/root/sub-store \
            xream/sub-store:latest
          sleep 10
          curl -s http://localhost:25500/api/version

      # 3️⃣ 下载订阅链接
      - name: Download subscription
        run: |
          SUB_LINK="https://example.com/subscription.yaml"
          curl -L "$SUB_LINK" -o base.yaml
          echo "✅ Subscription downloaded"

      # 4️⃣ 合并订阅 + JS 脚本
      - name: Merge with JS script
        run: |
          SCRIPT_FILE="./script.js"  # 仓库内 JS 脚本
          curl -L "http://localhost:25500/sub?target=clash&url=base.yaml&config=$SCRIPT_FILE" -o merged.yaml
          echo "✅ Merged YAML created"

      # 5️⃣ 推送到 gh-pages 分支
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
          force_orphan: true
        run: |
          mkdir -p docs
          mv merged.yaml docs/final.yaml
          echo "✅ final.yaml pushed to gh-pages branch"
