name: Build Final Config

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install axios js-yaml
      - run: node scripts/run-rewrite.js
        env:
          SUB_URL: ${{ secrets.SUB_URL }}
      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add output/
          git diff --quiet && git diff --staged --quiet || git commit -m "Update config.yaml"
          git push
